INSERT INTO tb_cv (name, job_title, description, image, phone, email, location) VALUES ('Nicolas Jones', 'Gerente de Marketing Digital', 'Possuo mais de 15 anos de expertise na criação e execução de estratégias inovadoras para impulsionar marcas. Com formação em marketing e pós-graduação em marketing digital, destaca-se por sua habilidade em analisar dados e criar campanhas integradas que transcendem as expectativas do mercado. O comprometimento com a excelência e a paixão por inovação são características que leva para as equipes que lidera.', 'https://cdn4.iconfinder.com/data/icons/diversity-v2-0-volume-05/64/fitness-trainer-asian-male-512.png', '(91)91634-5358', 'nicolas@gmail.com', 'Acará - PA');
INSERT INTO tb_cv (name, job_title, image, phone, email, location) VALUES ('Robert Wood', 'Design Gráfico', 'https://cdn4.iconfinder.com/data/icons/diversity-v2-0-volume-05/64/eye-glasses-asian-male-512.png', '(66)94098-9244', 'robert@gmail.com', 'Brasnorte - MT');
INSERT INTO tb_cv (name, job_title, image, phone, email, location) VALUES ('Kenya Cervantes', 'Promotora', 'https://cdn4.iconfinder.com/data/icons/diversity-v2-0-volume-02/64/black-woman-hair-style-2-512.png', '(11)95729-3432', 'kenya@gmail.com', 'Diadema - SP');
INSERT INTO tb_cv (name, job_title, image, phone, email, location) VALUES ('Fernando Damasceno', 'Procurador', 'https://cdn4.iconfinder.com/data/icons/diversity-v2-0-volume-02/64/black-dreadlock-male-tee-shirt-512.png', '(92)93119-0539', 'fernando@gmail.com', 'Anori - AM');
INSERT INTO tb_cv (name, job_title, image, phone, email, location) VALUES ('Lucas Alvarez', 'Escrivão de Polícia Civil', 'https://cdn0.iconfinder.com/data/icons/diversity-v2-0-volume-08/64/hipsters-white-male-512.png', '(71)93274-7429', 'lucas@gmail.com', 'Floresta Azul - BA');
INSERT INTO tb_cv (name, job_title, image, phone, email, location) VALUES ('Mariana Carvalho', 'Dermatologista', 'https://cdn4.iconfinder.com/data/icons/diversity-v2-0-volume-06/64/tank-toop-white-female-512.png', '(84)90033-8732', 'mariana@gmail.com', 'Acari - RN');
INSERT INTO tb_cv (name, job_title, image, phone, email, location) VALUES ('Rosângela Alves', 'Nutricionista', 'https://cdn0.iconfinder.com/data/icons/diversity-v2-0-volume-08/64/woman-round-glasses-hair-bun-black-512.png', '(11)91462-9348', 'rosangela@gmail.com', 'Guarulhos - SP');
INSERT INTO tb_cv (name, job_title, image, phone, email, location) VALUES ('Amanda Reiter', 'Desenvolvedora Mobile', 'https://cdn4.iconfinder.com/data/icons/diversity-v2-0-volume-03/64/blacksmith-white-female-512.png', '(53)91467-9325', 'amanda@gmail.com', 'Porto Alegre - RS');
INSERT INTO tb_cv (name, job_title, image, phone, email, location) VALUES ('Vanessa Winter', 'Engenheira Ambiental', 'https://cdn4.iconfinder.com/data/icons/diversity-v2-0-volume-03/64/business-casual-white-female-512.png', '(85)91754-5742', 'vanessa@gmail.com', 'Tarrafas - CE');
INSERT INTO tb_cv (name, job_title, image, phone, email, location) VALUES ('Ramón Castro', 'Neurocirurgião', 'https://cdn4.iconfinder.com/data/icons/diversity-v2-0-volume-03/64/blacksmith-asian-male-512.png', '(98)97310-7324', 'ramon@gmail.com', 'Campos Lindos - TO');
INSERT INTO tb_cv (name, job_title, image, phone, email, location) VALUES ('Diana Diamond', 'Adiministrador de Banco de Dados', 'https://cdn4.iconfinder.com/data/icons/diversity-v2-0-volume-05/64/wavy-hair-woman-african-512.png', '(99)91429-4012', 'diana@gmail.com', 'São Luís - MA');
INSERT INTO tb_cv (name, job_title, image, phone, email, location) VALUES ('Olivia Olsen', 'Gerente de Projetos', 'https://cdn4.iconfinder.com/data/icons/diversity-v2-0-volume-05/64/flower-girl-6-512.png', '(11)98734-3269', 'olivia@gmail.com', 'Hortolândia - SP');
INSERT INTO tb_cv (name, job_title, image, phone, email, location) VALUES ('Isla Ramos', 'Analista de Business Intelligence', 'https://cdn4.iconfinder.com/data/icons/diversity-v2-0-volume-05/64/flower-girl-6-512.png', '(99)96228-5355', 'isla@gmail.com', 'Açailândia - MA');
INSERT INTO tb_cv (name, job_title, image, phone, email, location) VALUES ('Benjamin Barbosa', 'Engenheiro de Software', 'https://cdn0.iconfinder.com/data/icons/diversity-v2-0-volume-08/64/sweater-man-black-512.png', '(83)91645-9348', 'beijamim@gmail.com', 'Campina Grande - PB');
INSERT INTO tb_cv (name, job_title, phone, email, location) VALUES ('Ethan Alves', 'Arquiteto de Soluções', '(11)98711-7663', 'ethan@gmail.com', 'Campinas - SP');
INSERT INTO tb_cv (name, job_title, phone, email, location) VALUES ('Valentin Fernandes', 'Gestor de Recursos Humanos', '(53)91656-4684', 'valentin@gmail.com', ' Linha Nova - RS');
INSERT INTO tb_cv (name, job_title, phone, email, location) VALUES ('Arthur Borges', 'Psicólogo Jurídico', '(91)91234-5678', 'arthur@gmail.com', 'Viseu - PA ');
INSERT INTO tb_cv (name, job_title, phone, email, location) VALUES ('Thomas Ribeiro', 'Geólogo', '(66)98329-9452', 'thomas@gmail.com', 'Porto Estrela - MT');
INSERT INTO tb_cv (name, job_title, phone, email, location) VALUES ('Alessio Ferreira', 'Engenheiro Elétrico', '(85)90822-7426', 'alessio@gmail.com', 'Madalena - CE');
INSERT INTO tb_cv (name, job_title, phone, email, location) VALUES ('Beatrice Scott', 'Meteoróloga', '(98)90873-8358', 'beatrice@gmail.com', 'Nova Olinda - TO');
INSERT INTO tb_cv (name, job_title, phone, email, location) VALUES ('Eleonora Montanari', 'Gestora de Qualidade de Software', '(85)91873-5743', 'eleonora@gmail.com', 'Elisiário - CE');
INSERT INTO tb_cv (name, job_title, phone, email, location) VALUES ('Isabel Silvestri', 'Administradora de Redes', '(53)91432-3563', 'isabel@gmail.com', 'Gramado - RS');

INSERT INTO tb_education (cv_id, course, institution, status, academic_degree, start_date, end_date) VALUES (1, 'Marketing', 'Universidade de Ciências e Tecnologias', 'Concluído', 'Graduação', '2017-01-01', '2020-12-31');
INSERT INTO tb_education (cv_id, course, institution, status, academic_degree, start_date, end_date) VALUES (1, 'Maketing Digital', 'Centro de Estudos Superiores', 'Concluído', 'Especialização', '2021-07-01', '2022-07-31');
INSERT INTO tb_education (cv_id, course, institution, status, academic_degree, start_date, end_date) VALUES (1, 'Mídias Sociais', 'Faculdade de Tecnologia', 'Cursando', 'Especialização', '2023-07-01', '2024-03-31');


INSERT INTO tb_experience (cv_id, job_title, company, working_day, start_date) VALUES (1, 'Gerente de Marketing Digital', 'Nortif', 'Integral', '2024-01-01');
INSERT INTO tb_section (cv_id, title) VALUES (1, 'Habilidades');
INSERT INTO tb_item (section_id, name, description, start_date) VALUES (1, 'Google Analytics', 'Conhecimento na ferrameta Google Analytics voltado a mensuração de resultados ', '2021-06-01');